### ISSUE TITLE
Collection.Find method (probable) bug

### ISSUE THREAD

**Issue by alkaest2002** [techlayer/espresso.js#16] opened 2015-05-02 14:50 UTC
Hi Artemi.
I was trying to find a model in a collection, passing some of its attributes, but without the id.
Contrary to my expectations, the collection's find method yielded "undefined", although I was certain that there was the model whose attributes I was looking for.
I think I may have found a possible issue.

Changing (from line 80 onwards)
<pre>
isEqual: function(attr) {
    for (var key in attr) {
      if (!isEqual(attr[key], this[key])) return false;
    }
    return true;
  },
</pre>

To

<pre>
isEqual: function(attr) {
    for (var key in attr) {
      if (isEqual(attr[key], this[key])) return true;
    }
    return false;
  },
</pre>

made it possible to find a model in a collection, by passing some of its attributes (without the id).

**Comment by alkaest2002** [comment] 2015-05-03 08:51
Sorry, Artemi. Made a mistake. Cannot make find method to look for models in a collection without passing the id

**Comment by alkaest2002** [comment] 2015-05-04 19:08
This may be the problem:

<pre>
  // find index of matching object, eg: findIndex({ id: 1 });
  findIndex: function(attr) {
    var items = this.items, isEqual = Model.prototype.isEqual, id;
    if (this.idAttribute in attr) id = this.idAttribute;
    for (var i = 0, len = items.length; i < len; i++) {
      if (id) {
        if (attr[id] === items[i][id]) return i;
      } else if (isEqual.call(attr, items[i])) return i;      
    }
    return -1;
  },
</pre>

I changed the elseif part from:
<pre>
else if (isEqual.call(attr, items[i])) return i; 
</pre>

to:

<pre>
else if (isEqual.call(items[i], attr)) return i; 
</pre>

And collection find method works (I think) as expected

**Comment by falafflepotatoe** [comment] 2015-05-20 11:51
good post, i ended up making my own .matching(matchingobj) method because i had the same problem

**Comment by falafflepotatoe** [comment] 2015-05-20 12:07
interestingly enough (not really but...)

im getting an error i cannot reproduce, when updating a collection that has arrays in it (myobj.somearr)

specifically the line  in collection.set()

 if (isEqual(this.items[index], value)) return;

returns when ive updated my object and the result is no change event is emitted..

it only happens sometimes and i cannot figure out why, i wonder if this could be related

**Comment by falafflepotatoe** [comment] 2015-05-20 12:25
anyway passing this on to artemi, im not a JS expert

tbh i have no idea about .call and .apply but heres what i found:

isEqual.call(obj1, { a: samevalues}) 
and
isEqual(obj1, {a: samevalues})

return different things

https://jsfiddle.net/f902s94n/

just what i found, might not be relevant at all

(perhaps .call returns its own value it seems)

**Comment by falafflepotatoe** [comment] 2015-05-22 20:14
bumping for OP, i think you want .filter() -- i edited my post above with an explanation.

**Comment by akrymski** [comment] 2015-05-28 03:04
Thanks for spotting the bug, just pushed a fix

**Closed by akrymski** 2015-05-28 03:04 UTC
